# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 14:06
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'draft'), ('published', 'published'), ('hidden', 'hidden')], default='draft', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('body', model_utils.fields.SplitField(no_excerpt_field=True, verbose_name='body')),
                ('pub_date', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='published date/time', when=set(['published']))),
                ('slug', autoslug.fields.AutoSlugField(allow_unicode=True, editable=False, max_length=255, populate_from='title', unique_for_date='pub_date')),
                ('featured', models.BooleanField(default=False, verbose_name='featured')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('lead', models.TextField(blank=True, verbose_name='lead')),
                ('comment_enabled', models.BooleanField(default=True, verbose_name='comments enabled')),
                ('_body_excerpt', models.TextField(editable=False)),
            ],
            options={
                'verbose_name': 'Post',
                'get_latest_by': 'pub_date',
                'ordering': ('-pub_date',),
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
